services:
  - type: web
    name: nba-api
    env: python
    rootDir: .
    buildCommand: pip install -U pip && pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT

  - type: static
    name: nba-frontend
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE
        fromService:
          type: web
          name: nba-api
          property: url
